export enum HttpStatusCode {
  OK = 200,
  CREATED = 201,
  NO_CONTENT = 204,

  BAD_REQUEST = 400,
  UNAUTHORIZED = 401,
  FORBIDDEN = 403,
  NOT_FOUND = 404,

  INTERNAL_SERVER_ERROR = 500,
  SERVICE_UNAVAILABLE = 503,
  GATEWAY_TIMEOUT = 504,
}

export enum GenericErrorKeys {
  OK = 'SUCCESS_OK',
  CREATED = 'SUCCESS_CREATED',
  NO_CONTENT = 'SUCCESS_NO_CONTENT',

  BAD_REQUEST = 'ERROR_BAD_REQUEST',
  UNAUTHORIZED = 'ERROR_UNAUTHORIZED',
  FORBIDDEN = 'ERROR_FORBIDDEN',
  NOT_FOUND = 'ERROR_NOT_FOUND',

  INTERNAL_SERVER_ERROR = 'ERROR_INTERNAL_SERVER_ERROR',
  SERVICE_UNAVAILABLE = 'ERROR_SERVICE_UNAVAILABLE',
  GATEWAY_TIMEOUT = 'ERROR_GATEWAY_TIMEOUT',
}
