export enum TErrorKeys {
 MISSING_DATA = "MISSING_DATA",
 WRONG_EMAIL_OR_PWD = "WRONG_EMAIL_OR_PWD",
 ACCESS_REQUEST_FAILED = "ACCESS_REQUEST_FAILED",
 CANT_PROCESS_ACCESS_REQUEST = "CANT_PROCESS_ACCESS_REQUEST",
 INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR",
 UNAUTHORIZED = "UNAUTHORIZED"
}